# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dilutionSolution.ui'
#
# Created: Wed Jan  9 11:37:18 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayoutWidget = QtGui.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 211, 561))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.desConcLabel = QtGui.QLabel(self.verticalLayoutWidget)
        self.desConcLabel.setObjectName("desConcLabel")
        self.verticalLayout.addWidget(self.desConcLabel)
        self.desConcValue = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.desConcValue.setObjectName("desConcValue")
        self.verticalLayout.addWidget(self.desConcValue)
        self.desConcUnits = QtGui.QListWidget(self.verticalLayoutWidget)
        self.desConcUnits.setObjectName("desConcUnits")
        QtGui.QListWidgetItem(self.desConcUnits)
        QtGui.QListWidgetItem(self.desConcUnits)
        QtGui.QListWidgetItem(self.desConcUnits)
        QtGui.QListWidgetItem(self.desConcUnits)
        QtGui.QListWidgetItem(self.desConcUnits)
        QtGui.QListWidgetItem(self.desConcUnits)
        QtGui.QListWidgetItem(self.desConcUnits)
        QtGui.QListWidgetItem(self.desConcUnits)
        QtGui.QListWidgetItem(self.desConcUnits)
        QtGui.QListWidgetItem(self.desConcUnits)
        QtGui.QListWidgetItem(self.desConcUnits)
        QtGui.QListWidgetItem(self.desConcUnits)
        QtGui.QListWidgetItem(self.desConcUnits)
        QtGui.QListWidgetItem(self.desConcUnits)
        QtGui.QListWidgetItem(self.desConcUnits)
        QtGui.QListWidgetItem(self.desConcUnits)
        self.verticalLayout.addWidget(self.desConcUnits)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.desVolLabel = QtGui.QLabel(self.verticalLayoutWidget)
        self.desVolLabel.setObjectName("desVolLabel")
        self.verticalLayout.addWidget(self.desVolLabel)
        self.desVolValue = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.desVolValue.setObjectName("desVolValue")
        self.verticalLayout.addWidget(self.desVolValue)
        self.desVolUnits = QtGui.QListWidget(self.verticalLayoutWidget)
        self.desVolUnits.setObjectName("desVolUnits")
        QtGui.QListWidgetItem(self.desVolUnits)
        QtGui.QListWidgetItem(self.desVolUnits)
        QtGui.QListWidgetItem(self.desVolUnits)
        QtGui.QListWidgetItem(self.desVolUnits)
        self.verticalLayout.addWidget(self.desVolUnits)
        self.verticalLayoutWidget_2 = QtGui.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(280, 10, 291, 561))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stockConcLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.stockConcLabel.setObjectName("stockConcLabel")
        self.verticalLayout_2.addWidget(self.stockConcLabel)
        self.stockConcValue = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.stockConcValue.setObjectName("stockConcValue")
        self.verticalLayout_2.addWidget(self.stockConcValue)
        self.stockConcUnits = QtGui.QListWidget(self.verticalLayoutWidget_2)
        self.stockConcUnits.setObjectName("stockConcUnits")
        QtGui.QListWidgetItem(self.stockConcUnits)
        QtGui.QListWidgetItem(self.stockConcUnits)
        QtGui.QListWidgetItem(self.stockConcUnits)
        QtGui.QListWidgetItem(self.stockConcUnits)
        QtGui.QListWidgetItem(self.stockConcUnits)
        QtGui.QListWidgetItem(self.stockConcUnits)
        QtGui.QListWidgetItem(self.stockConcUnits)
        QtGui.QListWidgetItem(self.stockConcUnits)
        QtGui.QListWidgetItem(self.stockConcUnits)
        QtGui.QListWidgetItem(self.stockConcUnits)
        QtGui.QListWidgetItem(self.stockConcUnits)
        QtGui.QListWidgetItem(self.stockConcUnits)
        QtGui.QListWidgetItem(self.stockConcUnits)
        QtGui.QListWidgetItem(self.stockConcUnits)
        QtGui.QListWidgetItem(self.stockConcUnits)
        QtGui.QListWidgetItem(self.stockConcUnits)
        self.verticalLayout_2.addWidget(self.stockConcUnits)
        self.label = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.buttonBox = QtGui.QDialogButtonBox(self.verticalLayoutWidget_2)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dilution Solution", None, QtGui.QApplication.UnicodeUTF8))
        self.desConcLabel.setText(QtGui.QApplication.translate("Dialog", "Desired Concentration", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.desConcUnits.isSortingEnabled()
        self.desConcUnits.setSortingEnabled(False)
        self.desConcUnits.item(0).setText(QtGui.QApplication.translate("Dialog", "Mol/L", None, QtGui.QApplication.UnicodeUTF8))
        self.desConcUnits.item(1).setText(QtGui.QApplication.translate("Dialog", "mMol/L", None, QtGui.QApplication.UnicodeUTF8))
        self.desConcUnits.item(2).setText(QtGui.QApplication.translate("Dialog", "mMol/mL", None, QtGui.QApplication.UnicodeUTF8))
        self.desConcUnits.item(3).setText(QtGui.QApplication.translate("Dialog", "mMol/uL", None, QtGui.QApplication.UnicodeUTF8))
        self.desConcUnits.item(4).setText(QtGui.QApplication.translate("Dialog", "uMol/L", None, QtGui.QApplication.UnicodeUTF8))
        self.desConcUnits.item(5).setText(QtGui.QApplication.translate("Dialog", "uMol/mL", None, QtGui.QApplication.UnicodeUTF8))
        self.desConcUnits.item(6).setText(QtGui.QApplication.translate("Dialog", "uMol/uL", None, QtGui.QApplication.UnicodeUTF8))
        self.desConcUnits.item(7).setText(QtGui.QApplication.translate("Dialog", "nMol/L", None, QtGui.QApplication.UnicodeUTF8))
        self.desConcUnits.item(8).setText(QtGui.QApplication.translate("Dialog", "nMol/mL", None, QtGui.QApplication.UnicodeUTF8))
        self.desConcUnits.item(9).setText(QtGui.QApplication.translate("Dialog", "nMol/uL", None, QtGui.QApplication.UnicodeUTF8))
        self.desConcUnits.item(10).setText(QtGui.QApplication.translate("Dialog", "nMol/pL", None, QtGui.QApplication.UnicodeUTF8))
        self.desConcUnits.item(11).setText(QtGui.QApplication.translate("Dialog", "pMol/L", None, QtGui.QApplication.UnicodeUTF8))
        self.desConcUnits.item(12).setText(QtGui.QApplication.translate("Dialog", "pMol/mL", None, QtGui.QApplication.UnicodeUTF8))
        self.desConcUnits.item(13).setText(QtGui.QApplication.translate("Dialog", "pMol/uL", None, QtGui.QApplication.UnicodeUTF8))
        self.desConcUnits.item(14).setText(QtGui.QApplication.translate("Dialog", "pMol/nL", None, QtGui.QApplication.UnicodeUTF8))
        self.desConcUnits.item(15).setText(QtGui.QApplication.translate("Dialog", "pMol/pL", None, QtGui.QApplication.UnicodeUTF8))
        self.desConcUnits.setSortingEnabled(__sortingEnabled)
        self.desVolLabel.setText(QtGui.QApplication.translate("Dialog", "Desired Volume", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.desVolUnits.isSortingEnabled()
        self.desVolUnits.setSortingEnabled(False)
        self.desVolUnits.item(0).setText(QtGui.QApplication.translate("Dialog", "L", None, QtGui.QApplication.UnicodeUTF8))
        self.desVolUnits.item(1).setText(QtGui.QApplication.translate("Dialog", "mL", None, QtGui.QApplication.UnicodeUTF8))
        self.desVolUnits.item(2).setText(QtGui.QApplication.translate("Dialog", "uL", None, QtGui.QApplication.UnicodeUTF8))
        self.desVolUnits.item(3).setText(QtGui.QApplication.translate("Dialog", "pL", None, QtGui.QApplication.UnicodeUTF8))
        self.desVolUnits.setSortingEnabled(__sortingEnabled)
        self.stockConcLabel.setText(QtGui.QApplication.translate("Dialog", "Stock Concentration", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.stockConcUnits.isSortingEnabled()
        self.stockConcUnits.setSortingEnabled(False)
        self.stockConcUnits.item(0).setText(QtGui.QApplication.translate("Dialog", "Mol/L", None, QtGui.QApplication.UnicodeUTF8))
        self.stockConcUnits.item(1).setText(QtGui.QApplication.translate("Dialog", "mMol/L", None, QtGui.QApplication.UnicodeUTF8))
        self.stockConcUnits.item(2).setText(QtGui.QApplication.translate("Dialog", "mMol/mL", None, QtGui.QApplication.UnicodeUTF8))
        self.stockConcUnits.item(3).setText(QtGui.QApplication.translate("Dialog", "mMol/uL", None, QtGui.QApplication.UnicodeUTF8))
        self.stockConcUnits.item(4).setText(QtGui.QApplication.translate("Dialog", "uMol/L", None, QtGui.QApplication.UnicodeUTF8))
        self.stockConcUnits.item(5).setText(QtGui.QApplication.translate("Dialog", "uMol/mL", None, QtGui.QApplication.UnicodeUTF8))
        self.stockConcUnits.item(6).setText(QtGui.QApplication.translate("Dialog", "uMol/uL", None, QtGui.QApplication.UnicodeUTF8))
        self.stockConcUnits.item(7).setText(QtGui.QApplication.translate("Dialog", "nMol/L", None, QtGui.QApplication.UnicodeUTF8))
        self.stockConcUnits.item(8).setText(QtGui.QApplication.translate("Dialog", "nMol/mL", None, QtGui.QApplication.UnicodeUTF8))
        self.stockConcUnits.item(9).setText(QtGui.QApplication.translate("Dialog", "nMol/uL", None, QtGui.QApplication.UnicodeUTF8))
        self.stockConcUnits.item(10).setText(QtGui.QApplication.translate("Dialog", "nMol/pL", None, QtGui.QApplication.UnicodeUTF8))
        self.stockConcUnits.item(11).setText(QtGui.QApplication.translate("Dialog", "pMol/L", None, QtGui.QApplication.UnicodeUTF8))
        self.stockConcUnits.item(12).setText(QtGui.QApplication.translate("Dialog", "pMol/mL", None, QtGui.QApplication.UnicodeUTF8))
        self.stockConcUnits.item(13).setText(QtGui.QApplication.translate("Dialog", "pMol/uL", None, QtGui.QApplication.UnicodeUTF8))
        self.stockConcUnits.item(14).setText(QtGui.QApplication.translate("Dialog", "pMol/nL", None, QtGui.QApplication.UnicodeUTF8))
        self.stockConcUnits.item(15).setText(QtGui.QApplication.translate("Dialog", "pMol/pL", None, QtGui.QApplication.UnicodeUTF8))
        self.stockConcUnits.setSortingEnabled(__sortingEnabled)
        self.label.setText(QtGui.QApplication.translate("Dialog", "Volume Stock Solution:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Liters:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "mL:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "uL:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Volume Solution:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Liters:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "mL:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "uL:", None, QtGui.QApplication.UnicodeUTF8))

